### ISSUE TITLE
Library not longer works in the latest version of Firefox (59)

### ISSUE THREAD

**Issue by akmaslov** [laaglu/lib-gwt-svg#26]
It seems like with the latest patch, the methods that this library was relying on to mutate SVGPathSegList are no longer supported:
https://bugzilla.mozilla.org/show_bug.cgi?id=1436438

This effectively means that any method that does this throws an error, for instance:

 public final native OMSVGPathSeg appendItem(OMSVGPathSeg newItem) throws JavaScriptException /*-{
    return this.@org.vectomatic.dom.svg.OMSVGPathSegList::ot.appendItem(newItem);
  }-*/;

Effectively, this means none of our SVG code renders in Firefox. In the same issue they also mention that Chrome has deprecated and removed these methods over a year ago, though strangely we haven't seen any issues there.

**Comment by akmaslov** [comment]
The fix might as simple as including an updated pathseg.js polyfill from here:
https://github.com/progers/pathseg/blob/master/pathseg.js

Not sure yet.

**Comment by laaglu** [comment]
Thanks for reporting the regression. Indeed it seems to be caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1436438 (which is not mentioned in FF 59 release notes :-( https://developer.mozilla.org/en-US/Firefox/Releases/59). I think you are right about the fix too. pathseg.js has been upgraded specially to support FF59+, I will make a fix for that asap

**Comment by akmaslov** [comment]
That's great! Just noticed the commit; thanks for the swift response. Can you deploy an updated artifact to mvn central?

**Comment by laaglu** [comment]
It's already there :-)
